//
// import '../models/food_item.dart';
//
// class FoodService {
//   // Returns a stream of 16 food items
//   Stream<List<FoodItem>> getFoods() {
//     final foods = [
//       FoodItem(
//         id: '1',
//         name: 'Burger',
//         description: 'Juicy burger with cheese, lettuce, tomato, served fresh daily.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvaenfbZBNLAYNJ5RRQZv4L15hpK0efJttzg&s',
//         price: 5.99,
//         discount: 10,
//         available: true,
//         rating: 4,
//         vendorId: 'vendor_1',
//         vendorName: 'Canteen',
//       ),
//       FoodItem(
//         id: '2',
//         name: 'Pizza',
//         description: 'Cheesy veggie pizza topped with onions, peppers, sauce, delicious slice.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt6zKlWn0zYSDXv2XwOIDGWfsfi1OVDWmAcw&s',
//         price: 7.99,
//         discount: 15,
//         available: true,
//         rating: 5,
//         vendorId: 'vendor_1',
//         vendorName: 'Canteen',
//       ),
//       FoodItem(
//         id: '3',
//         name: 'Pasta',
//         description: 'Italian pasta cooked with tomato sauce, parmesan, and fresh herbs.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYpqCujWuKeNyecqDQejefoRlxEQXSImzcow&s',
//         price: 6.49,
//         discount: 0,
//         available: true,
//         rating: 4,
//         vendorId: 'vendor_2',
//         vendorName: 'Snack Stall',
//       ),
//       FoodItem(
//         id: '4',
//         name: 'Sandwich',
//         description: 'Club sandwich stacked with turkey, bacon, lettuce, mayo, toasted bread.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVwvp0_Z8SP3x5L8E_vp1YM4f9Z8DDOh6yHg&s',
//         price: 4.99,
//         discount: 5,
//         available: true,
//         rating: 4,
//         vendorId: 'vendor_2',
//         vendorName: 'Snack Stall',
//       ),
//       FoodItem(
//         id: '5',
//         name: 'Salad',
//         description: 'Garden salad with lettuce, cucumber, tomato, vinaigrette, healthy choice.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiHrXGdGEH1S-WhZ_pvKd4beNo5V3crLPR5g&s',
//         price: 3.99,
//         discount: 0,
//         available: true,
//         rating: 3,
//         vendorId: 'vendor_3',
//         vendorName: 'Healthy Corner',
//       ),
//       FoodItem(
//         id: '6',
//         name: 'Ice Cream',
//         description: 'Chocolate ice cream scoop, creamy texture, chilled summer dessert delight.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRecdXVPJ_bP7GthAiacGerqxNXOcGV5GVhyg&s',
//         price: 2.99,
//         discount: 20,
//         available: true,
//         rating: 5,
//         vendorId: 'vendor_3',
//         vendorName: 'Healthy Corner',
//       ),
//       FoodItem(
//         id: '7',
//         name: 'Donut',
//         description: 'Fluffy donut ring with sugar glaze, sweet morning snack.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzbKPD-pHx20kL7lDRHIZmb8fVdgFxdPNfGQ&s',
//         price: 1.99,
//         discount: 0,
//         available: true,
//         rating: 4,
//         vendorId: 'vendor_4',
//         vendorName: 'Bakery',
//       ),
//       FoodItem(
//         id: '8',
//         name: 'Cake',
//         description: 'Chocolate cake slice with frosting, moist layers, dessert lover’s dream.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ544u_y1mcEeUmxBwRh5XDjqySo2S4Oxyccg&s',
//         price: 4.50,
//         discount: 10,
//         available: true,
//         rating: 5,
//         vendorId: 'vendor_4',
//         vendorName: 'Bakery',
//       ),
//       FoodItem(
//         id: '9',
//         name: 'Fries',
//         description: 'Golden crispy fries salted lightly, perfect side snack anytime.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG4jynlETrmyjCefub6SdZEdJwpm0Jh5Z8ag&s',
//         price: 2.50,
//         discount: 0,
//         available: true,
//         rating: 4,
//         vendorId: 'vendor_5',
//         vendorName: 'Fast Food',
//       ),
//       FoodItem(
//         id: '10',
//         name: 'Sushi',
//         description: 'Fresh salmon sushi rolls wrapped in seaweed, served with wasabi.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmMkkzlRtrMUzvBZHGQl_eH67DKmuFUyR1Xw&s',
//         price: 8.99,
//         discount: 5,
//         available: true,
//         rating: 5,
//         vendorId: 'vendor_5',
//         vendorName: 'Fast Food',
//       ),
//       FoodItem(
//         id: '11',
//         name: 'Steak',
//         description: 'Grilled steak seasoned perfectly, tender juicy bites, savory evening meal.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn7nhYE8roJhidaydcezEFU-DDQgZRDfthwA&s',
//         price: 12.99,
//         discount: 10,
//         available: true,
//         rating: 5,
//         vendorId: 'vendor_6',
//         vendorName: 'Grill House',
//       ),
//       FoodItem(
//         id: '12',
//         name: 'Pancakes',
//         description: 'Fluffy pancakes served with syrup and butter, breakfast delight.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFGLWZ2tVLOYB3VyZM9bAnvznsZpyiQWGJoQ&s',
//         price: 4.99,
//         discount: 0,
//         available: true,
//         rating: 4,
//         vendorId: 'vendor_6',
//         vendorName: 'Grill House',
//       ),
//       FoodItem(
//         id: '13',
//         name: 'Chicken Wings',
//         description: 'Spicy chicken wings, oven baked, perfect appetizer for any occasion.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuDFVYGvcHlAWetjIPb3H67MAwLq1HojnJNQ&s',
//         price: 6.99,
//         discount: 15,
//         available: true,
//         rating: 4,
//         vendorId: 'vendor_7',
//         vendorName: 'BBQ Corner',
//       ),
//       FoodItem(
//         id: '14',
//         name: 'Soup',
//         description: 'Hot vegetable soup with fresh herbs, comforting and healthy.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSUPy_QmUX431AG9ycAXf1Wp78zYF5KDeg-w&s',
//         price: 3.50,
//         discount: 0,
//         available: true,
//         rating: 4,
//         vendorId: 'vendor_7',
//         vendorName: 'BBQ Corner',
//       ),
//       FoodItem(
//         id: '15',
//         name: 'Coffee',
//         description: 'Hot black coffee freshly brewed, energizing and aromatic drink.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTee-1umSbOsRzyi_ObE7-Gt4nrW_LFY1Cnww&s',
//         price: 1.99,
//         discount: 0,
//         available: true,
//         rating: 4,
//         vendorId: 'vendor_8',
//         vendorName: 'Coffee Shop',
//       ),
//       FoodItem(
//         id: '16',
//         name: 'Tea',
//         description: 'Green tea with soothing aroma, perfect for relaxing moments.',
//         image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrVbAhRPYQWTNO8qNjM_8j-E0xYt7ToByzdw&s',
//         price: 1.50,
//         discount: 0,
//         available: true,
//         rating: 3,
//         vendorId: 'vendor_8',
//         vendorName: 'Coffee Shop',
//       ),
//     ];
//
//     return Stream<List<FoodItem>>.periodic(
//         const Duration(milliseconds: 500), (_) => foods);
//   }
// }


import '../models/food_item.dart';

class FoodService {
  // Returns a stream of 16 food items
  Stream<List<FoodItem>> getFoods() {
    final foods = [
      FoodItem(
        id: '1',
        name: 'Burger',
        description: 'Juicy burger with cheese, lettuce, tomato, served fresh daily.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvaenfbZBNLAYNJ5RRQZv4L15hpK0efJttzg&s',
        price: 5.99,
        discount: 10,
        available: true,
        rating: 4,
        vendorId: 'vendor_1',
        vendorName: 'Canteen',
      ),
      FoodItem(
        id: '2',
        name: 'Pizza',
        description: 'Cheesy veggie pizza topped with onions, peppers, sauce, delicious slice.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSt6zKlWn0zYSDXv2XwOIDGWfsfi1OVDWmAcw&s',
        price: 7.99,
        discount: 15,
        available: true,
        rating: 5,
        vendorId: 'vendor_1',
        vendorName: 'Canteen',
      ),
      FoodItem(
        id: '3',
        name: 'Pasta',
        description: 'Italian pasta cooked with tomato sauce, parmesan, and fresh herbs.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYpqCujWuKeNyecqDQejefoRlxEQXSImzcow&s',
        price: 6.49,
        discount: 0,
        available: true,
        rating: 4,
        vendorId: 'vendor_2',
        vendorName: 'Snack Stall',
      ),
      FoodItem(
        id: '4',
        name: 'Sandwich',
        description: 'Club sandwich stacked with turkey, bacon, lettuce, mayo, toasted bread.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVwvp0_Z8SP3x5L8E_vp1YM4f9Z8DDOh6yHg&s',
        price: 4.99,
        discount: 5,
        available: true,
        rating: 4,
        vendorId: 'vendor_2',
        vendorName: 'Snack Stall',
      ),
      FoodItem(
        id: '5',
        name: 'Salad',
        description: 'Garden salad with lettuce, cucumber, tomato, vinaigrette, healthy choice.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiHrXGdGEH1S-WhZ_pvKd4beNo5V3crLPR5g&s',
        price: 3.99,
        discount: 0,
        available: true,
        rating: 3,
        vendorId: 'vendor_3',
        vendorName: 'Healthy Corner',
      ),
      FoodItem(
        id: '6',
        name: 'Ice Cream',
        description: 'Chocolate ice cream scoop, creamy texture, chilled summer dessert delight.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRecdXVPJ_bP7GthAiacGerqxNXOcGV5GVhyg&s',
        price: 2.99,
        discount: 20,
        available: true,
        rating: 5,
        vendorId: 'vendor_3',
        vendorName: 'Healthy Corner',
      ),
      FoodItem(
        id: '7',
        name: 'Donut',
        description: 'Fluffy donut ring with sugar glaze, sweet morning snack.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzbKPD-pHx20kL7lDRHIZmb8fVdgFxdPNfGQ&s',
        price: 1.99,
        discount: 0,
        available: true,
        rating: 4,
        vendorId: 'vendor_4',
        vendorName: 'Bakery',
      ),
      FoodItem(
        id: '8',
        name: 'Cake',
        description: 'Chocolate cake slice with frosting, moist layers, dessert lover’s dream.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ544u_y1mcEeUmxBwRh5XDjqySo2S4Oxyccg&s',
        price: 4.50,
        discount: 10,
        available: true,
        rating: 5,
        vendorId: 'vendor_4',
        vendorName: 'Bakery',
      ),
      FoodItem(
        id: '9',
        name: 'Fries',
        description: 'Golden crispy fries salted lightly, perfect side snack anytime.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG4jynlETrmyjCefub6SdZEdJwpm0Jh5Z8ag&s',
        price: 2.50,
        discount: 0,
        available: true,
        rating: 4,
        vendorId: 'vendor_5',
        vendorName: 'Fast Food',
      ),
      FoodItem(
        id: '10',
        name: 'Sushi',
        description: 'Fresh salmon sushi rolls wrapped in seaweed, served with wasabi.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmMkkzlRtrMUzvBZHGQl_eH67DKmuFUyR1Xw&s',
        price: 8.99,
        discount: 5,
        available: true,
        rating: 5,
        vendorId: 'vendor_5',
        vendorName: 'Fast Food',
      ),
      FoodItem(
        id: '11',
        name: 'Steak',
        description: 'Grilled steak seasoned perfectly, tender juicy bites, savory evening meal.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn7nhYE8roJhidaydcezEFU-DDQgZRDfthwA&s',
        price: 12.99,
        discount: 10,
        available: true,
        rating: 5,
        vendorId: 'vendor_6',
        vendorName: 'Grill House',
      ),
      FoodItem(
        id: '12',
        name: 'Pancakes',
        description: 'Fluffy pancakes served with syrup and butter, breakfast delight.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFGLWZ2tVLOYB3VyZM9bAnvznsZpyiQWGJoQ&s',
        price: 4.99,
        discount: 0,
        available: true,
        rating: 4,
        vendorId: 'vendor_6',
        vendorName: 'Grill House',
      ),
      FoodItem(
        id: '13',
        name: 'Chicken Wings',
        description: 'Spicy chicken wings, oven baked, perfect appetizer for any occasion.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuDFVYGvcHlAWetjIPb3H67MAwLq1HojnJNQ&s',
        price: 6.99,
        discount: 15,
        available: true,
        rating: 4,
        vendorId: 'vendor_7',
        vendorName: 'BBQ Corner',
      ),
      FoodItem(
        id: '14',
        name: 'Soup',
        description: 'Hot vegetable soup with fresh herbs, comforting and healthy.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSUPy_QmUX431AG9ycAXf1Wp78zYF5KDeg-w&s',
        price: 3.50,
        discount: 0,
        available: true,
        rating: 4,
        vendorId: 'vendor_7',
        vendorName: 'BBQ Corner',
      ),
      FoodItem(
        id: '15',
        name: 'Coffee',
        description: 'Hot black coffee freshly brewed, energizing and aromatic drink.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTee-1umSbOsRzyi_ObE7-Gt4nrW_LFY1Cnww&s',
        price: 1.99,
        discount: 0,
        available: true,
        rating: 4,
        vendorId: 'vendor_8',
        vendorName: 'Coffee Shop',
      ),
      FoodItem(
        id: '16',
        name: 'Tea',
        description: 'Green tea with soothing aroma, perfect for relaxing moments.',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrVbAhRPYQWTNO8qNjM_8j-E0xYt7ToByzdw&s',
        price: 1.50,
        discount: 0,
        available: true,
        rating: 3,
        vendorId: 'vendor_8',
        vendorName: 'Coffee Shop',
      ),
    ];

    // Return a stream of all foods
    return Stream<List<FoodItem>>.periodic(
        const Duration(milliseconds: 500), (_) => foods);
  }

  // New function: Get foods by vendor ID
  Stream<List<FoodItem>> getFoodsByVendor(String vendorId) {
    return getFoods().map((foodList) =>
        foodList.where((food) => food.vendorId == vendorId).toList());
  }
}
