// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChuwzKYyvId_r-m7_fItBG5_NLs0rM18s',
    appId: '1:1002809091074:web:11e06b3c4846f767bf331b',
    messagingSenderId: '1002809091074',
    projectId: 'restaurent-app-a4dd0',
    authDomain: 'restaurent-app-a4dd0.firebaseapp.com',
    storageBucket: 'restaurent-app-a4dd0.firebasestorage.app',
    measurementId: 'G-E910JYM5VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Bx8VKSP3uYF1HsNAvhSZ35hLXDNJ-gQ',
    appId: '1:1002809091074:android:82c04338e4ed5ee3bf331b',
    messagingSenderId: '1002809091074',
    projectId: 'restaurent-app-a4dd0',
    storageBucket: 'restaurent-app-a4dd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDflTw3TB7JMc8s3aXA9Potu09ntz6p__w',
    appId: '1:1002809091074:ios:330d61c396184590bf331b',
    messagingSenderId: '1002809091074',
    projectId: 'restaurent-app-a4dd0',
    storageBucket: 'restaurent-app-a4dd0.firebasestorage.app',
    iosBundleId: 'com.example.restaurentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDflTw3TB7JMc8s3aXA9Potu09ntz6p__w',
    appId: '1:1002809091074:ios:330d61c396184590bf331b',
    messagingSenderId: '1002809091074',
    projectId: 'restaurent-app-a4dd0',
    storageBucket: 'restaurent-app-a4dd0.firebasestorage.app',
    iosBundleId: 'com.example.restaurentManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChuwzKYyvId_r-m7_fItBG5_NLs0rM18s',
    appId: '1:1002809091074:web:b7ea83a4f4cd2d2ebf331b',
    messagingSenderId: '1002809091074',
    projectId: 'restaurent-app-a4dd0',
    authDomain: 'restaurent-app-a4dd0.firebaseapp.com',
    storageBucket: 'restaurent-app-a4dd0.firebasestorage.app',
    measurementId: 'G-H3EFVXL230',
  );
}
